server:
  port: 8182
  error:
    whitelabel:
      enabled: false

auth:
  msg: "Welcome to ClozingTag Auth Default Application"
  build-version: 1.0.0
  base-url: ${BASE_URL:http://localhost:8181}
  environment: ${ENVIRONMENT:sandbox}
  oauth:
    clientId: ${CLIENT_ID:closing.tag}
    clientSecret: ${CLIENT_SECRET:closing.tag@25}
    redirectUri: 
      login: https://clzingtag.com/authorized

  jwt:
    key:
      public-key: classpath:app.pub
      private-key: classpath:app.key
      id: clozingtag
    persistence:
      password: password
      salt: 626F6F746966756C

spring:
  application:
    name: clozingtag-auth-service
  profiles:
    active: ${ACTIVE_PROFILE:default} #default
#  cloud:
#    config:
#      uri: ${CONFIG_SERVER:http://localhost:8888}
#      username: ${CONFIG_USER:clozing_tag_user}
#      password: ${CONFIG_PASS:clozing_tag_pass}
#      discovery:
#        enabled: true
#        service-id: clozingtag-config-service
#      fail-fast: true
#      retry:
#        initial-interval: 1000
#        multiplier: 1.5
#        max-attempts: 10000
#        max-interval: 1500
#      enabled: true
  main:
    allow-bean-definition-overriding: true
  jpa:
    hibernate.ddl-auto: update
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: true
    database-platform: org.hibernate.dialect.PostgresPlusDialect
    generate-ddl: true
  sql:
    init:
      schema-locations:
        - classpath:oauth2-schema.sql
      mode: always
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ct_auth_service_db}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      initialization-fail-timeout: 0
 
info:
  app:
    name: Auth MicroService
    description: ClozingTag Auth Application
    version: 1.0.0
      
management:
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true
  tracing:
    sampling:
      probability: 1.0

  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true  


logging:
  pattern:
    console: "%clr(%d{HH:mm:ss.SSS}){blue} %clr(%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]){yellow} %clr(:){red} %clr(%m){faint}%n"
  level:
    com.clozingtag.peerfunding.auth.service: DEBUG


eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY_SERVER_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

openapi:
  service:
    title: Clozing Auth Service Docs
    version: 1.0.0
    url: ${GATEWAY_URL:http://localhost:8181/api/auth} #api gateway url
springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
